Linkup fucked me up again. Lost hours of work.

diff --git a/linkup b/linkup
--- a/linkup
+++ b/linkup
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+sudo echo 'Cache sudo credentials'
+
+GIT_CLEAN=$(git status --porcelain)
+if [[ -z $GIT_DIRTY ]]; then
+  echo "Git repo is dirty. Please commit or stash changes before updating."
+  exit 1
+fi
+
+OS = $(cat /etc/os-release | grep ^ID= | cut -d '=' -f 2)
+
 git submodule update --init
 
 update () {
@@ -27,6 +37,10 @@ rm -rf $HOME/scripts
 ln -s $PWD/scripts $HOME/scripts
 
 mk-dir-if-not-found $HOME/.ssh
+sudo chown -R $USER:$USER $HOME/.ssh
+chmod 700 $HOME/.ssh
+chmod 400 $HOME/.ssh/*
+chmod 600 $HOME/.ssh/known_hosts
 [[ -f $HOME/.ssh/config ]] && mv $HOME/.ssh/config{,.bkup}
 ln -s $PWD/ssh-config $HOME/.ssh/config
 
@@ -35,6 +49,8 @@ mk-dir-if-not-found $HOME/.cache/zsh
 mk-dir-if-not-found $HOME/.rstat/lib
 
 mk-dir-if-not-found $HOME/.ipython/profile_default
+[[ -f $HOME/.ipython/profile_default/ipython_config.py ]] &&
+  mv $HOME/.ipython/profile_default/ipython_config.py{,.bkup}
 ln -s $PWD/ipython_config.py $HOME/.ipython/profile_default/ipython_config.py
 
 # Assuming the submodule is populated
@@ -48,24 +64,84 @@ if [[ "$1" == "--vundle" || "$2" == "--vundle" ]]; then
   mkdir -p $HOME/.vim/bundle
   git clone 'https://github.com/VundleVim/Vundle.vim' \
       $HOME/.vim/bundle/Vundle.vim
-  vim +PluginInstall +qall
+  vim -u NONE +PluginInstall +qall
 fi
 
 rm -rf $HOME/.tmux/plugins/tpm
 git clone 'https://github.com/tmux-plugins/tpm' $HOME/.tmux/plugins/tpm
 
-rm -rf $HOME/.zprompt/pure
-git clone 'https://github.com/sindresorhus/pure.git' $HOME/.zprompt/pure
+if [[ "$OS" == "ubuntu" ]]; then
+  rm -rf $HOME/.zprompt/pure
+  git clone 'https://github.com/sindresorhus/pure.git' $HOME/.zprompt/pure
+fi
+
+if [[ "$OS" == "arch" ]]; then
+  if [[ -z "$(command -v paru)" ]]; then
+    parus -S zsh-pure-prompt-git
+  else
+    echo "paru not found. Install paru first and then zsh-pure-prompt-git"
+  fi
+fi
 
 if [[ "$1" == "--wsl" || "$2" == "--wsl" ]]; then
 
   sudo cp wsl.conf /etc/wsl.conf
-  sudo apt-get update && sudo apt-get upgrade
-  sudo apt-get install zsh fortune-mod cowsay x11-apps \
-    mlocate mupdf r-base vim-gtk3 unzip ripgrep mplayer \
-    virtualenv python3-pip tree dos2unix python3-tk \
-    fonts-firacode fonts-cascadia-code bat fd-find
-  pip install scipy pandas ipython statsmodels
+
+  if [[ "$OS" == "ubuntu" ]]; then
+    sudo apt-get update && sudo apt-get upgrade
+    sudo apt-get install -y \
+      bat \
+      cowsay \
+      dos2unix \
+      fd-find \
+      fonts-cascadia-code \
+      fonts-firacode \
+      fortune-mod \
+      plocate \
+      mplayer \
+      mupdf \
+      python3-pip \
+      python3-tk \
+      r-base \
+      ripgrep \
+      tree \
+      unzip \
+      vim-gtk3 \
+      virtualenv \
+      x11-apps \
+      zsh \
+
+    sudo ln -s /usr/bin/fdfind /usr/bin/fd
+    sudo ln -s /usr/bin/batcat /usr/bin/bat
+    sudo ln -s /usr/bin/python3 /usr/bin/python
+
+  fi
+
+ if [[ "$OS" == "arch" ]]; then
+    sudo pacman -Syyu
+    sudo pacman -S --needed \
+      bat \
+      cowsay \
+      dos2unix \
+      fd \
+      fortune-mod \
+      plocate \
+      mplayer \
+      mupdf \
+      python \
+      python-pip \
+      r \
+      ripgrep \
+      tree \
+      ttf-cascadia-code \
+      ttf-fira-code \
+      unzip \
+      vim \
+      python-virtualenv \
+      xorg-xclock \
+      zsh \
+  fi
+
   chsh
 
   MNT=/mnt
@@ -73,16 +149,17 @@ if [[ "$1" == "--wsl" || "$2" == "--wsl" ]]; then
     wslpath -u $(cmd.exe /c echo $1 2> /dev/null) | tr -d ''
   }
 
-  ln -s $MNT/c $HOME/c
-  ln -s $MNT/d $HOME/d
-  ln -s $MNT/c/Users/$(get_win_var %USERNAME%) $HOME/winhome
-  ln -s $HOME/winhome/Documents $HOME/doc
-  ln -s $HOME/winhome/Downloads $HOME/tmp
-  ln -s $(get_win_var %TMP%) $HOME/temp
+  [[ -d "$HOME/c" ]] || ln -s $MNT/c $HOME/c
+  [[ -d "$HOME/d" ]] || ln -s $MNT/d $HOME/d
+  [[ -d "$HOME/winhome" ]] || ln -s $MNT/c/Users/$(get_win_var %USERNAME%) $HOME/winhome
+  [[ -d "$HOME/doc" ]] || ln -s $HOME/winhome/Documents $HOME/doc
+  [[ -d "$HOME/tmp" ]] || ln -s $HOME/winhome/Downloads $HOME/tmp
+  [[ -d "$HOME/temp" ]] || ln -s $(get_win_var %TMP%) $HOME/temp
 
   mk-dir-if-not-found $HOME/.ssh
   sudo cp $HOME/winhome/.ssh/* $HOME/.ssh/
-  sudo chown $USER:$USER $HOME/.ssh/*
+  sudo chown -R $USER:$USER $HOME/.ssh
+  chmod 700 $HOME/.ssh
   chmod 400 $HOME/.ssh/*
   chmod 600 $HOME/.ssh/known_hosts
 
@@ -95,7 +172,9 @@ if [[ "$1" == "--wsl" || "$2" == "--wsl" ]]; then
     cp $PS_PROF $PS_DIR/
   fi
 
-  cat zshrc.wsl >> $HOME/.zshrc.more
+  ln -s zshrc.wsl >> $HOME/.zshrc.wsl
+  ln -s zshrc.docker >> $HOME/.zshrc.docker
+  touch .zshrc.more
 
   source zshrc.wsl; cp $PWD/windows-terminal-settings.json $WIN_TERM_SETTINGS
 
